### ISSUE TITLE
Email Application MVP

### ISSUE THREAD

**Issue by arunmr1980** [arunmr1980/aws-email-service#7]
### User Stories

- As a user I need to be able to send bulk emails and track status
- As a user I need to see individual failed email and see the failure reason
- As a user I need to be able to do corrections and retry
- As a user I need to monitor the system performance and failure rated in a date and time range

#### Phase 1

- [ ] The status must be updated and retrievable
- [ ] API to retrieve the status of emails send
- [ ] Users must be able to add attachments

#### Phase 2

- [ ] Suppression details must be accessible
- [ ] Reputation details need to be accessible
- [ ] Angular application to view status
- [ ] Dashboard for viewing stats
